import { getStore } from '@netlify/blobs';

const BASE = 'https://centraldetraspasos.com';

function slugify(text) {
  return String(text || '')
    .toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function getPropertyUrl(p) {
  return BASE + '/propiedad/' + slugify(p.title_es || p.title_en) + '-' + p.id;
}

const STATIC_PAGES = [
  {"loc":"https://centraldetraspasos.com/",
  "es":"https://centraldetraspasos.com/",
  "en":"https://centraldetraspasos.com/en/",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"1.0"},
  {"loc":"https://centraldetraspasos.com/propiedades",
  "es":"https://centraldetraspasos.com/propiedades",
  "en":"https://centraldetraspasos.com/en/propiedades",
  "last":"2026-06-16",
  "freq":"daily",
  "prio":"0.9"},
  {"loc":"https://centraldetraspasos.com/captacion",
  "es":"https://centraldetraspasos.com/captacion",
  "en":"https://centraldetraspasos.com/en/captacion",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/blog",
  "es":"https://centraldetraspasos.com/blog",
  "en":"https://centraldetraspasos.com/en/blog",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/aviso-legal",
  "es":"https://centraldetraspasos.com/aviso-legal",
  "en":"https://centraldetraspasos.com/en/aviso-legal",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.3"},
  {"loc":"https://centraldetraspasos.com/restaurantes",
  "es":"https://centraldetraspasos.com/restaurantes",
  "en":"https://centraldetraspasos.com/en/restaurantes",
  "last":"2026-06-18",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/bares",
  "es":"https://centraldetraspasos.com/bares",
  "en":"https://centraldetraspasos.com/en/bares",
  "last":"2026-06-18",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/locales-comerciales",
  "es":"https://centraldetraspasos.com/locales-comerciales",
  "en":"https://centraldetraspasos.com/en/locales-comerciales",
  "last":"2026-06-18",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/hosteleria",
  "es":"https://centraldetraspasos.com/hosteleria",
  "en":"https://centraldetraspasos.com/en/hosteleria",
  "last":"2026-06-18",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/teatinos",
  "es":"https://centraldetraspasos.com/teatinos",
  "en":"https://centraldetraspasos.com/en/teatinos",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/traspasos-marbella",
  "es":"https://centraldetraspasos.com/traspasos-marbella",
  "en":"https://centraldetraspasos.com/en/traspasos-marbella",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-malaga",
  "es":"https://centraldetraspasos.com/locales-malaga",
  "en":"https://centraldetraspasos.com/en/locales-malaga",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.8"},
  {"loc":"https://centraldetraspasos.com/locales-fuengirola",
  "es":"https://centraldetraspasos.com/locales-fuengirola",
  "en":"https://centraldetraspasos.com/en/locales-fuengirola",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-torremolinos",
  "es":"https://centraldetraspasos.com/locales-torremolinos",
  "en":"https://centraldetraspasos.com/en/locales-torremolinos",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-benalmadena",
  "es":"https://centraldetraspasos.com/locales-benalmadena",
  "en":"https://centraldetraspasos.com/en/locales-benalmadena",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-estepona",
  "es":"https://centraldetraspasos.com/locales-estepona",
  "en":"https://centraldetraspasos.com/en/locales-estepona",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-mijas",
  "es":"https://centraldetraspasos.com/locales-mijas",
  "en":"https://centraldetraspasos.com/en/locales-mijas",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-antequera",
  "es":"https://centraldetraspasos.com/locales-antequera",
  "en":"https://centraldetraspasos.com/en/locales-antequera",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-velez-malaga",
  "es":"https://centraldetraspasos.com/locales-velez-malaga",
  "en":"https://centraldetraspasos.com/en/locales-velez-malaga",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-nerja",
  "es":"https://centraldetraspasos.com/locales-nerja",
  "en":"https://centraldetraspasos.com/en/locales-nerja",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/locales-rincon-de-la-victoria",
  "es":"https://centraldetraspasos.com/locales-rincon-de-la-victoria",
  "en":"https://centraldetraspasos.com/en/locales-rincon-de-la-victoria",
  "last":"2026-06-16",
  "freq":"weekly",
  "prio":"0.7"},
  {"loc":"https://centraldetraspasos.com/blog/cuanto-cuesta-traspaso-restaurante-malaga.html",
  "es":"https://centraldetraspasos.com/blog/cuanto-cuesta-traspaso-restaurante-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/cuanto-cuesta-traspaso-restaurante-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/guia-precios-locales-zonas-malaga.html",
  "es":"https://centraldetraspasos.com/blog/guia-precios-locales-zonas-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/guia-precios-locales-zonas-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/como-financiar-traspaso-negocio-malaga.html",
  "es":"https://centraldetraspasos.com/blog/como-financiar-traspaso-negocio-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/como-financiar-traspaso-negocio-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-peluqueria-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-peluqueria-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-peluqueria-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-clinica-estetica-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-clinica-estetica-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-clinica-estetica-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-discoteca-pub-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-discoteca-pub-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-discoteca-pub-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-supermercado-fuengirola-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-supermercado-fuengirola-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-supermercado-fuengirola-malaga.html",
  "last":"2026-06-18",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-pizzeria-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-pizzeria-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-pizzeria-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-kebab-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-kebab-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-kebab-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-restaurante-teatinos-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-restaurante-teatinos-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-restaurante-teatinos-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/mejores-zonas-abrir-negocio-malaga.html",
  "es":"https://centraldetraspasos.com/blog/mejores-zonas-abrir-negocio-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/mejores-zonas-abrir-negocio-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/guia-traspaso-local-malaga.html",
  "es":"https://centraldetraspasos.com/blog/guia-traspaso-local-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/guia-traspaso-local-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/locales-restaurante-costa-del-sol.html",
  "es":"https://centraldetraspasos.com/blog/locales-restaurante-costa-del-sol.html",
  "en":"https://centraldetraspasos.com/en/blog/locales-restaurante-costa-del-sol.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/alquiler-local-comercial-malaga.html",
  "es":"https://centraldetraspasos.com/blog/alquiler-local-comercial-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/alquiler-local-comercial-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/invertir-locales-costa-del-sol.html",
  "es":"https://centraldetraspasos.com/blog/invertir-locales-costa-del-sol.html",
  "en":"https://centraldetraspasos.com/en/blog/invertir-locales-costa-del-sol.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/tasacion-negocio-malaga.html",
  "es":"https://centraldetraspasos.com/blog/tasacion-negocio-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/tasacion-negocio-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/licencia-actividad-malaga.html",
  "es":"https://centraldetraspasos.com/blog/licencia-actividad-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/licencia-actividad-malaga.html",
  "last":"2026-06-16",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-asador-restaurante-fuengirola.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-asador-restaurante-fuengirola.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-asador-restaurante-fuengirola.html",
  "last":"2026-06-25",
  "freq":"monthly",
  "prio":"0.6"},
  {"loc":"https://centraldetraspasos.com/blog/traspaso-restaurante-compas-victoria-malaga.html",
  "es":"https://centraldetraspasos.com/blog/traspaso-restaurante-compas-victoria-malaga.html",
  "en":"https://centraldetraspasos.com/en/blog/traspaso-restaurante-compas-victoria-malaga.html",
  "last":"2026-06-25",
  "freq":"monthly",
  "prio":"0.6"}
];

function staticBlock(p) {
  return [
    '    <loc>' + p.loc + '</loc>',
    '    <xhtml:link rel="alternate" hreflang="es" href="' + p.es + '"/>',
    '    <xhtml:link rel="alternate" hreflang="en" href="' + p.en + '"/>',
    '    <lastmod>' + p.last + '</lastmod>',
    '    <changefreq>' + p.freq + '</changefreq>',
    '    <priority>' + p.prio + '</priority>'
  ].join('\n');
}

function propBlock(p) {
  const last = String(p.updatedAt || p.createdAt || new Date().toISOString().slice(0, 10)).slice(0, 10);
  return [
    '    <loc>' + getPropertyUrl(p) + '</loc>',
    '    <lastmod>' + last + '</lastmod>',
    '    <changefreq>weekly</changefreq>',
    '    <priority>0.6</priority>'
  ].join('\n');
}

export async function handler() {
  let props = [];
  let dbg = '';
  try {
    const store = getStore('crm');
    const raw = await store.get('data', { type: 'text' });
    dbg = 'raw=' + (raw == null ? 'null' : 'len' + raw.length) + ' head=' + (raw != null ? raw.slice(0, 80) : '');
    const data = raw ? JSON.parse(raw) : {};
    props = (data.properties || []).filter(p => p.status === 'published').sort((a, b) => (a.id || 0) - (b.id || 0));
    dbg += ' | props=' + props.length;
  } catch (e) {
    dbg = 'EXC ' + (e && e.message ? e.message : e);
    console.error('sitemap: no se pudo leer el store', e);
  }
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- ' + dbg + ' -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...STATIC_PAGES.map(p => '  <url>\n' + staticBlock(p) + '\n  </url>'),
    ...props.map(p => '  <url>\n' + propBlock(p) + '\n  </url>'),
    '</urlset>'
  ].join('\n');
  return {
    statusCode: 200,
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
    body: xml
  };
}
