[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/aviso-legal"
  to = "/aviso-legal.html"
  status = 200

[[redirects]]
  from = "/traspasos-marbella"
  to = "/traspasos-marbella.html"
  status = 200

[[redirects]]
  from = "/locales-fuengirola"
  to = "/locales-fuengirola.html"
  status = 200

[[redirects]]
  from = "/locales-torremolinos"
  to = "/locales-torremolinos.html"
  status = 200

[[redirects]]
  from = "/locales-benalmadena"
  to = "/locales-benalmadena.html"
  status = 200

[[redirects]]
  from = "/locales-estepona"
  to = "/locales-estepona.html"
  status = 200

[[redirects]]
  from = "/locales-mijas"
  to = "/locales-mijas.html"
  status = 200

[[redirects]]
  from = "/locales-antequera"
  to = "/locales-antequera.html"
  status = 200

