[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/en/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/en"
  to = "/"
  status = 200

[[redirects]]
  from = "/propiedad/*"
  to = "/.netlify/functions/property-page/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/aviso-legal"
  to = "/aviso-legal.html"
  status = 200

[[redirects]]
  from = "/locales-malaga"
  to = "/locales-malaga.html"
  status = 200

[[redirects]]
  from = "/traspasos-marbella"
  to = "/traspasos-marbella.html"
  status = 200

[[redirects]]
  from = "/locales-marbella"
  to = "/traspasos-marbella.html"
  status = 200

[[redirects]]
  from = "/locales-fuengirola"
  to = "/locales-fuengirola.html"
  status = 200

[[redirects]]
  from = "/locales-torremolinos"
  to = "/locales-torremolinos.html"
  status = 200

[[redirects]]
  from = "/locales-benalmadena"
  to = "/locales-benalmadena.html"
  status = 200

[[redirects]]
  from = "/locales-estepona"
  to = "/locales-estepona.html"
  status = 200

[[redirects]]
  from = "/locales-mijas"
  to = "/locales-mijas.html"
  status = 200

[[redirects]]
  from = "/locales-antequera"
  to = "/locales-antequera.html"
  status = 200

[[redirects]]
  from = "/locales-velez-malaga"
  to = "/locales-velez-malaga.html"
  status = 200

[[redirects]]
  from = "/locales-nerja"
  to = "/locales-nerja.html"
  status = 200

[[redirects]]
  from = "/locales-rincon-de-la-victoria"
  to = "/locales-rincon-de-la-victoria.html"
  status = 200

[[redirects]]
  from = "/teatinos"
  to = "/teatinos.html"
  status = 200

